In [1]:
import numpy as np

a. Displaying Student  total number of student

In [2]:
studentScore = np.genfromtxt('data.csv', delimiter=',')
studentScore

array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4],
       [  6. ,  65.7,  29.1,  80.4],
       [  7. ,  88.2,  31.2,  77.8],
       [  8. ,  82.6,  70.9,  71.3],
       [  9. ,  58.6,  52.2,  31. ],
       [ 10. ,  84.1,  71.5,  25.1],
       [ 11. ,  84.5,  78.7,  93.4],
       [ 12. ,  63.6,  67.5,  63.9],
       [ 13. ,  15.7,  11.1,  82.5],
       [ 14. ,  76.8,  23.4,  99. ],
       [ 15. ,  99.8,  38.7,  78.5],
       [ 16. ,  29.5,  95.2,  96.4],
       [ 17. ,  36.3,  28.8,  56.6],
       [ 18. ,  79.4,  96.4,  15.7],
       [ 19. ,  75. ,  12.2,  72.1],
       [ 20. ,  95.1,  83.3,  47. ],
       [ 21. ,  86.4,  84.6,  53.8],
       [ 22. ,  50.4,  65.5,  68.3],
       [ 23. ,  19.3,  18.9,  54.8],
       [ 24. ,  19.8,  51.5,  49.5],
       [ 25. ,  20.2,  17.2,  53.7],
       [ 26. ,  46.8,  93.3,  69.5],
       [ 27. ,  27.7,  26. ,  48.7],
 

In [3]:
g = studentScore.shape[0]
print("THe Total Number Of Students Are: ", g)

THe Total Number Of Students Are:  250


 b. Creating a copy of studentScore as fscores Displaying list of Five student

In [4]:
fscore = studentScore.copy()

In [7]:
fscore[:5]

array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4]])

In [9]:
studentScore

array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4],
       [  6. ,  65.7,  29.1,  80.4],
       [  7. ,  88.2,  31.2,  77.8],
       [  8. ,  82.6,  70.9,  71.3],
       [  9. ,  58.6,  52.2,  31. ],
       [ 10. ,  84.1,  71.5,  25.1],
       [ 11. ,  84.5,  78.7,  93.4],
       [ 12. ,  63.6,  67.5,  63.9],
       [ 13. ,  15.7,  11.1,  82.5],
       [ 14. ,  76.8,  23.4,  99. ],
       [ 15. ,  99.8,  38.7,  78.5],
       [ 16. ,  29.5,  95.2,  96.4],
       [ 17. ,  36.3,  28.8,  56.6],
       [ 18. ,  79.4,  96.4,  15.7],
       [ 19. ,  75. ,  12.2,  72.1],
       [ 20. ,  95.1,  83.3,  47. ],
       [ 21. ,  86.4,  84.6,  53.8],
       [ 22. ,  50.4,  65.5,  68.3],
       [ 23. ,  19.3,  18.9,  54.8],
       [ 24. ,  19.8,  51.5,  49.5],
       [ 25. ,  20.2,  17.2,  53.7],
       [ 26. ,  46.8,  93.3,  69.5],
       [ 27. ,  27.7,  26. ,  48.7],
 

c. adding the CA Column 

In [40]:
CA_column = np.round(((studentScore[:, 1]) + (studentScore[:, 2]))/2, decimals=1)
scoreWithCA = np.column_stack((studentScore, CA_column))
scoreWithCA [: 3]

array([[  1. ,  59.4,  26.3,  81.8,  42.8],
       [  2. ,  65.9,  29.6, 100. ,  47.8],
       [  3. ,  70.7,  56.3,  70.5,  63.5]])

d. Adding the FM column

In [46]:
FM_column = np.round((scoreWithCA[:,3])*0.6 + (scoreWithCA[:, 4])*0.4, decimals=1)
scoreWithFM= np.column_stack((scoreWithCA, FM_column))
scoreWithFM [: 3]

array([[  1. ,  59.4,  26.3,  81.8,  42.8,  66.2],
       [  2. ,  65.9,  29.6, 100. ,  47.8,  79.1],
       [  3. ,  70.7,  56.3,  70.5,  63.5,  67.7]])

e.  Display how many students have passed, how students have failed and sum of students passed and failed

In [ ]:
pasi = scoreWithFM [:,5] >= 40
studentPass = np.sum(pasi)
feli = scoreWithFM [:,5] < 40
studentFailed = np.sum(feli)
print("Students Passed = ",studentPass )
print("\n")
print("Students Failed = ", studentFailed)
print("\n")
print(f"Sum of Students Passed and Failed are {studentFailed+studentPass}")


In [5]:
import numpy as np
studentScore = np.genfromtxt('data.csv', delimiter=',')
studentScore


array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4],
       [  6. ,  65.7,  29.1,  80.4],
       [  7. ,  88.2,  31.2,  77.8],
       [  8. ,  82.6,  70.9,  71.3],
       [  9. ,  58.6,  52.2,  31. ],
       [ 10. ,  84.1,  71.5,  25.1],
       [ 11. ,  84.5,  78.7,  93.4],
       [ 12. ,  63.6,  67.5,  63.9],
       [ 13. ,  15.7,  11.1,  82.5],
       [ 14. ,  76.8,  23.4,  99. ],
       [ 15. ,  99.8,  38.7,  78.5],
       [ 16. ,  29.5,  95.2,  96.4],
       [ 17. ,  36.3,  28.8,  56.6],
       [ 18. ,  79.4,  96.4,  15.7],
       [ 19. ,  75. ,  12.2,  72.1],
       [ 20. ,  95.1,  83.3,  47. ],
       [ 21. ,  86.4,  84.6,  53.8],
       [ 22. ,  50.4,  65.5,  68.3],
       [ 23. ,  19.3,  18.9,  54.8],
       [ 24. ,  19.8,  51.5,  49.5],
       [ 25. ,  20.2,  17.2,  53.7],
       [ 26. ,  46.8,  93.3,  69.5],
       [ 27. ,  27.7,  26. ,  48.7],
 

In [6]:
CA_column = np.round(((studentScore[:, 1]) + (studentScore[:, 2]))/2, decimals=1)
scoreWithCA = np.column_stack((studentScore, CA_column))
scoreWithCA [: 3]

array([[  1. ,  59.4,  26.3,  81.8,  42.8],
       [  2. ,  65.9,  29.6, 100. ,  47.8],
       [  3. ,  70.7,  56.3,  70.5,  63.5]])

In [7]:
FM_column = np.round((scoreWithCA[:,3])*0.6 + (scoreWithCA[:, 4])*0.4, decimals=1)
scoreWithFM= np.column_stack((scoreWithCA, FM_column))
scoreWithFM [: 3]

array([[  1. ,  59.4,  26.3,  81.8,  42.8,  66.2],
       [  2. ,  65.9,  29.6, 100. ,  47.8,  79.1],
       [  3. ,  70.7,  56.3,  70.5,  63.5,  67.7]])

In [11]:
fail_mark = 40
fail = np.where (scoreWithFM[:,-1]< fail_mark)[0]

for index in fail[:8]:
    print("SN:", scoreWithFM[index, 0],
                  "Test1:", scoreWithFM[index, 1],
                  "Test2:", scoreWithFM[index, 2],
                  "UE:", scoreWithFM[index, 3],
                  "CA:", scoreWithFM[index, 4],
                  "FM:", scoreWithFM[index, 5])
            


SN: 4.0 Test1: 27.5 Test2: 19.4 UE: 36.7 CA: 23.4 FM: 31.4
SN: 25.0 Test1: 20.2 Test2: 17.2 UE: 53.7 CA: 18.7 FM: 39.7
SN: 27.0 Test1: 27.7 Test2: 26.0 UE: 48.7 CA: 26.8 FM: 39.9
SN: 32.0 Test1: 65.4 Test2: 50.7 UE: 10.2 CA: 58.0 FM: 29.3
SN: 33.0 Test1: 25.4 Test2: 43.9 UE: 39.5 CA: 34.6 FM: 37.5
SN: 37.0 Test1: 30.7 Test2: 57.6 UE: 21.9 CA: 44.2 FM: 30.8
SN: 38.0 Test1: 85.5 Test2: 46.0 UE: 12.0 CA: 65.8 FM: 33.5
SN: 40.0 Test1: 50.6 Test2: 41.8 UE: 34.8 CA: 46.2 FM: 39.4


h.

In [19]:
PF = scoreWithFM[:,-1]
remark = np.where(PF >= 40, 'PASS', 'FAIL')
column_PF = np.column_stack((scoreWithFM,remark))
column_PF



array([['1.0', '59.4', '26.3', ..., '42.8', '66.2', 'PASS'],
       ['2.0', '65.9', '29.6', ..., '47.8', '79.1', 'PASS'],
       ['3.0', '70.7', '56.3', ..., '63.5', '67.7', 'PASS'],
       ...,
       ['248.0', '79.1', '65.3', ..., '72.2', '87.9', 'PASS'],
       ['249.0', '50.6', '65.7', ..., '58.2', '75.5', 'PASS'],
       ['250.0', '41.6', '68.5', ..., '55.0', '78.5', 'PASS']],
      dtype='<U32')

i

In [23]:
studentP = remark == "PASS"
P = np.sum(studentP)
studentF = remark == "FAIL"
F = np.sum(studentF)
print( "Students Passed = ", P)
print("students Fail = ", F)
print("Sum of Students Passed and Failed = ", P+F)

Students Passed =  193
students Fail =  57
Sum of Students Passed and Failed =  250


J.

In [38]:
max_test1 = np.max(scoreWithFM[:,1], axis=0)
min_test1 = np.min(scoreWithFM[:,1], axis=0)
avg_test1 = np.average(scoreWithFM[:,1], axis=0)

max_test2 = np.max(scoreWithFM[:,2], axis=0)
min_test2 = np.min(scoreWithFM[:,2], axis=0)
avg_test2 = np.average(scoreWithFM[:,2], axis=0)

max_ue = np.max(scoreWithFM[:,3], axis=0)
min_ue = np.min(scoreWithFM[:,3], axis=0)
avg_ue = np.average(scoreWithFM[:,3], axis=0)

max_ca = np.max(scoreWithFM[:,4], axis=0)
min_ca = np.min(scoreWithFM[:,4], axis=0)
avg_ca = np.average(scoreWithFM[:,4], axis=0)

max_fm = np.max(scoreWithFM[:,5], axis=0)
min_fm = np.min(scoreWithFM[:,5], axis=0)
avg_fm = np.average(scoreWithFM[:,5], axis=0)

print("{:<12} {:<10} {:<10} {:<10} {:<10}".format("", "Test1", "Test2", "UE", "CA", "FM"))
print("="*50)
print("{:<12} {:<10} {:<10} {:<10} {:<10}".format("Minimum", min_test1, min_test2, min_ue, min_ca, min_fm))
print("{:<12} {:<10} {:<10} {:<10} {:<10}".format("Maximum", max_test1, max_test2, max_ue, max_ca, max_fm))
print("{:<12} {:<10} {:<10} {:<10} {:<10}".format("Average", avg_test1, avg_test2, avg_ue, avg_ca, avg_fm))






             Test1      Test2      UE         CA        
Minimum      10.2       10.3       10.1       11.6      
Maximum      99.8       99.4       100.0      94.9      
Average      54.1336    54.956399999999995 56.2512    54.546    


k.

In [46]:

def calculate_grade(score):
    grade_ranges = [(70, 100), (60, 70), (50, 60), (40, 50), (35, 40), (0, 35)]
    grade_letters = ['A', 'B+', 'B', 'C', 'D', 'E']

    for i, (lower, upper) in enumerate(grade_ranges):
        if lower <= score <= upper:
            return grade_letters[i]
    return "N/A"

def get_student_scores(student_id):
    try:
        # user anaingiza serial number
        while student_id < 1 or student_id > len(scoreWithFM):
            print("SN {} specified is outside the range, please try again.".format(student_id))
            student_id = int(input("Enter student serial number: "))
        
        # Kupata  student data
        student_data = scoreWithFM[student_id - 1]
        sn, test1, test2, ue, ca, fm = student_data
        grade = calculate_grade(fm)
        student_remark = "PASS" if remark[student_id - 1] == 'PASS' else "FAIL"
        

        print("Student serial number entered is:", student_id)
        print("Test 1 =", test1)
        print("Test 2 =", test2)
        print("UE =", ue)
        print("CA =", ca)
        print("FM =", fm)
        print("Grade =", grade)
        print("Remark =", student_remark)
    except ValueError:
        print("Invalid input. Please enter a valid integer serial number.")

# kuingiza taarifa za user
try:
    student_id = int(input("Enter student serial number: "))
    get_student_scores(student_id)
except ValueError:
    print("Invalid input. Please enter a valid integer serial number.")


SN 0 specified is outside the range, please try again.
SN 0 specified is outside the range, please try again.
Student serial number entered is: 250
Test 1 = 41.6
Test 2 = 68.5
UE = 94.2
CA = 55.0
FM = 78.5
Grade = A
Remark = PASS


l

In [53]:
new_student_data = [len(scoreWithFM) + 1, 45.6, 76.4, 65.5, 0, 0]
new_student_ca = (new_student_data[1]+new_student_data[2])/2
new_student_fm = (new_student_ca*0.4) +(new_student_data[3]*0.6)
new_student_data[4] = new_student_ca
new_student_data[5] = new_student_fm
scoreswithFMNew = np.append(scoreWithFM, [new_student_data], axis=0)

scoreswithFMNew[-3:]

array([[249. ,  50.6,  65.7,  87. ,  58.2,  75.5],
       [250. ,  41.6,  68.5,  94.2,  55. ,  78.5],
       [251. ,  45.6,  76.4,  65.5,  61. ,  63.7]])

m

In [54]:
scoreswithFMNew

array([[  1. ,  59.4,  26.3,  81.8,  42.8,  66.2],
       [  2. ,  65.9,  29.6, 100. ,  47.8,  79.1],
       [  3. ,  70.7,  56.3,  70.5,  63.5,  67.7],
       ...,
       [249. ,  50.6,  65.7,  87. ,  58.2,  75.5],
       [250. ,  41.6,  68.5,  94.2,  55. ,  78.5],
       [251. ,  45.6,  76.4,  65.5,  61. ,  63.7]])