In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [4]:
a[0]

1

In [6]:
a[5]

6

In [7]:
import time
import sys

b =  range(1000)
print(sys.getsizeof(5)*len(b))

In [10]:
c = np.arange(1000)
print(c.size*c.itemsize)

8000


 Basic operation

In [13]:
g = np.array([[1,2],[3,4],[5,6]])
print(g)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
g.ndim


2

In [15]:
g.itemsize

8

In [16]:
a.shape

(6,)

In [22]:
a.shape[0]

6

In [23]:
a

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [25]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [26]:
a.shape

(3, 2)

In [27]:
a.itemsize

8

In [29]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.complex64)

In [30]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
print("STRING CONCATENATION EXAMPLE")
print(np.char.add(['Habari', 'Mambo'], ['Python', 'ML']))

STRING CONCATENATION EXAMPLE
['HabariPython' 'MamboML']


In [35]:
print(np.char.center("Habari", 20, fillchar="*"))

*******Habari*******


In [36]:
print(np.char.capitalize('i am python king'))

I am python king


In [37]:
print(np.char.upper('i am python king'))

I AM PYTHON KING


In [38]:
print(np.char.split('i am python king'))

['i', 'am', 'python', 'king']


In [40]:
print(np.char.strip(['mango', 'admin','aninta'],'n'))

['mango' 'admi' 'aninta']


In [41]:
print(np.char.join([':','-'], ['dmy','ymd']))

['d:m:y' 'y-m-d']


In [42]:
print(np.char.replace('He is a python king', 'He', 'She'))

She is a python king


Array Manipulation

In [44]:
# Changing Shape

In [46]:
x = np.arange(9)
print("The Original Array: ")
print(x)
print()
y = x.reshape(3,3)
print("modified Array: ")
print(y)
 

The Original Array: 
[0 1 2 3 4 5 6 7 8]

modified Array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
print(y.flatten())

[0 1 2 3 4 5 6 7 8]


In [48]:
i = np.arange(12).reshape(4,3)
print(i)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [51]:
i=np.transpose(i)
print(i)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [54]:
a = np.arange(8).reshape(2,2,2)

In [55]:
print (a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


Arithematics Operations

In [56]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
b = np.array([10,10,10])
print(b)

[10 10 10]


In [60]:
print (np.add(a,b))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [61]:
print(np.subtract(a,b))

[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


In [62]:
print(np.multiply(a,b))

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [63]:
print(np.divide(a,b))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


Slicing

In [64]:
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
print (g[:5])


[0 1 2 3 4]


In [69]:
print (slice(2,9,2))

slice(2, 9, 2)


Iterating Over Array

In [71]:
a = np.arange(0,45,5).reshape(3,3)
print(a)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [72]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


Iteration Order (C-style and F-style

In [73]:
print(a)
for x in np.nditer(a, order="C"):
    print(x) 
    
print("------------------------------------------------------")    

for x in np.nditer(a, order="F"):
    print(x)   
    

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
------------------------------------------------------
0
15
30
5
20
35
10
25
40


Joining Arrays

In [74]:
 x = np.array([[1,2],[3,4]])
print("first array: ", x)

first array:  [[1 2]
 [3 4]]


In [75]:
y = np.array([[5,6],[7,8]])
print("second array: ", y)


second array:  [[5 6]
 [7 8]]


In [82]:
print("first array: ", x)
print("second array: ", y)
print('\n')
print("joining the two array along axix 0 :")
print(np.concatenate((x,y)))
print('\n')
print("joining the two array along axix 1 :")
print(np.concatenate((x,y), axis=1))

first array:  [[1 2]
 [3 4]]
second array:  [[5 6]
 [7 8]]


joining the two array along axix 0 :
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


joining the two array along axix 1 :
[[1 2 5 6]
 [3 4 7 8]]


Spliting Array

In [84]:
a = np.arange(9)
print (a)
print(np.split(a,3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Resizing an Array

In [89]:
d = np.array([[1,2,3],[4,5,6]])
print(d)
print(d.shape)
print("\n")
e = np.resize(a,(3,2))
print(e)
print(e.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


[[0 1]
 [2 3]
 [4 5]]
(3, 2)


Histogram

Statistics

In [91]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [92]:
np.min(stats)

1

In [93]:
np.max(stats)

6

In [94]:
np.sum(stats)

21

Stacking Vectors

In [95]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v2,v1])

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

Loading Data From File

In [119]:
filedata = np.genfromtxt('data.csv', delimiter=',')
filedata.astype('int64')
(filedata)


array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4],
       [  6. ,  65.7,  29.1,  80.4],
       [  7. ,  88.2,  31.2,  77.8],
       [  8. ,  82.6,  70.9,  71.3],
       [  9. ,  58.6,  52.2,  31. ],
       [ 10. ,  84.1,  71.5,  25.1],
       [ 11. ,  84.5,  78.7,  93.4],
       [ 12. ,  63.6,  67.5,  63.9],
       [ 13. ,  15.7,  11.1,  82.5],
       [ 14. ,  76.8,  23.4,  99. ],
       [ 15. ,  99.8,  38.7,  78.5],
       [ 16. ,  29.5,  95.2,  96.4],
       [ 17. ,  36.3,  28.8,  56.6],
       [ 18. ,  79.4,  96.4,  15.7],
       [ 19. ,  75. ,  12.2,  72.1],
       [ 20. ,  95.1,  83.3,  47. ],
       [ 21. ,  86.4,  84.6,  53.8],
       [ 22. ,  50.4,  65.5,  68.3],
       [ 23. ,  19.3,  18.9,  54.8],
       [ 24. ,  19.8,  51.5,  49.5],
       [ 25. ,  20.2,  17.2,  53.7],
       [ 26. ,  46.8,  93.3,  69.5],
       [ 27. ,  27.7,  26. ,  48.7],
 

In [145]:
print(filedata > 50)

[[False  True False  True]
 [False  True False  True]
 [False  True  True  True]
 [False False False False]
 [False False False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True  True  True]
 [False  True  True False]
 [False  True  True False]
 [False  True  True  True]
 [False  True  True  True]
 [False False False  True]
 [False  True False  True]
 [False  True False  True]
 [False False  True  True]
 [False False False  True]
 [False  True  True False]
 [False  True False  True]
 [False  True  True False]
 [False  True  True  True]
 [False  True  True  True]
 [False False False  True]
 [False False  True False]
 [False False False  True]
 [False False  True  True]
 [False False False False]
 [False False False  True]
 [False  True  True False]
 [False False  True False]
 [False  True  True False]
 [False  True  True False]
 [False False False False]
 [False False False  True]
 [False False  True False]
 [False  True False  True]
 [False False  True False]
 

In [113]:
filedata[filedata > 50]

array([ 59.4,  81.8,  65.9, 100. ,  70.7,  56.3,  70.5,  96.4,  65.7,
        80.4,  88.2,  77.8,  82.6,  70.9,  71.3,  58.6,  52.2,  84.1,
        71.5,  84.5,  78.7,  93.4,  63.6,  67.5,  63.9,  82.5,  76.8,
        99. ,  99.8,  78.5,  95.2,  96.4,  56.6,  79.4,  96.4,  75. ,
        72.1,  95.1,  83.3,  86.4,  84.6,  53.8,  50.4,  65.5,  68.3,
        54.8,  51.5,  53.7,  93.3,  69.5,  71.2,  77.7,  80.5,  68.1,
        71. ,  75.6,  65.4,  50.7,  76.2,  80.7,  99. ,  60. ,  57.6,
        85.5,  76.8,  66.5,  99.5,  50.6,  59. ,  88.8,  58.9,  71.1,
        60.9,  71.3,  65.3,  59.7,  89.1,  84.8,  50.9,  80.4,  67.5,
        58.9,  71.5,  76.9,  51. ,  92. ,  52. ,  71.9,  53. ,  54. ,
        51.7,  57.6,  55. ,  63.8,  86.8,  56. ,  58.8,  62.6,  57. ,
        67.8,  50.4,  57.1,  58. ,  92.1,  75.9,  59. ,  57.8,  53.3,
        60. ,  67.1,  79.3,  61. ,  96. ,  62. ,  89.9,  87.1,  63. ,
        89.8,  97.4,  64. ,  61.6,  78.6,  65. ,  84.8,  74.5,  66. ,
        67. ,  83.9,

In [114]:
np.any(filedata > 50, axis = 0)

array([ True,  True,  True,  True])

In [115]:
((filedata > 50)& (filedata<100))

array([[False,  True, False,  True],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False, False],
 

In [131]:
d = np.where (filedata[:6]<= 50, 'P', 'F')
d


array([['P', 'F', 'P', 'F'],
       ['P', 'F', 'P', 'F'],
       ['P', 'F', 'F', 'F'],
       ['P', 'P', 'P', 'P'],
       ['P', 'P', 'P', 'F'],
       ['P', 'F', 'P', 'F']], dtype='<U1')

In [138]:
filedata = np.genfromtxt('data.csv', delimiter=',')

In [139]:
filedata

array([[  1. ,  59.4,  26.3,  81.8],
       [  2. ,  65.9,  29.6, 100. ],
       [  3. ,  70.7,  56.3,  70.5],
       [  4. ,  27.5,  19.4,  36.7],
       [  5. ,  45.2,  27.4,  96.4],
       [  6. ,  65.7,  29.1,  80.4],
       [  7. ,  88.2,  31.2,  77.8],
       [  8. ,  82.6,  70.9,  71.3],
       [  9. ,  58.6,  52.2,  31. ],
       [ 10. ,  84.1,  71.5,  25.1],
       [ 11. ,  84.5,  78.7,  93.4],
       [ 12. ,  63.6,  67.5,  63.9],
       [ 13. ,  15.7,  11.1,  82.5],
       [ 14. ,  76.8,  23.4,  99. ],
       [ 15. ,  99.8,  38.7,  78.5],
       [ 16. ,  29.5,  95.2,  96.4],
       [ 17. ,  36.3,  28.8,  56.6],
       [ 18. ,  79.4,  96.4,  15.7],
       [ 19. ,  75. ,  12.2,  72.1],
       [ 20. ,  95.1,  83.3,  47. ],
       [ 21. ,  86.4,  84.6,  53.8],
       [ 22. ,  50.4,  65.5,  68.3],
       [ 23. ,  19.3,  18.9,  54.8],
       [ 24. ,  19.8,  51.5,  49.5],
       [ 25. ,  20.2,  17.2,  53.7],
       [ 26. ,  46.8,  93.3,  69.5],
       [ 27. ,  27.7,  26. ,  48.7],
 

In [144]:
filedata.shape[0]

250